name: Run Telegram Bot 24/7
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run every 6 hours to restart the bot (GitHub Actions limit)
    - cron: '0 */6 * * *'

# CRITICAL: Prevent multiple instances from running simultaneously
concurrency:
  group: telegram-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours maximum
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "Starting Telegram Bot..."
          python bot.py
